import type { Metadata } from "next";
import * as React from "react";
import "./globals.css"
import Providers from "@/components/Providers";
import TopNav from "@/components/navbar/TopNav";


export const metadata: Metadata = {
  title: "Next.js Full Stack App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopNav />
            <main  className={'container mx-auto p-10'}>
              {children}
            </main>
        </Providers>
      </body>
    </html>
  );
}
